local _ = require("lib/underscore")

describe("string functions", function()
  describe("#split", function()
    it("splits a string on each character", function()
      assert.same(_.split("asdf"),{"a","s","d","f"})
      assert.same(_.split(""),{})
    end)

    it("returns an empty array with non-string values", function()
      assert.same(_.split({}),{})
      assert.same(_.split(nil),{})
      assert.same(_.split(123),{})
      assert.same(_.split(function() end),{})
    end)

    describe("with a specific split string", function()
      it("can split a specific characters", function()
        assert.same(_.split("a|b|c|d", "|"), {"a","b","c","d"})
        assert.same(_.split("a 1 c 2", " "), {"a","1","c","2"})
        assert.same(_.split("a\tb\tc\td", "\t"), {"a","b","c","d"})
      end)

      it("can split using Lua pattern matchers", function()
        assert.same(_.split("a   b c     d", "%s+"), {"a","b","c","d"})
        assert.same(_.split("a1b2c3d4e", "%d"), {"a","b","c","d","e"})
      end)

      it("can split on whole words", function()
        assert.same(_.split("arabbitbrabbitc", "rabbit"), {"a","b","c"})
      end)
    end)
  end)
end)
